# Generated by Django 5.0.1 on 2024-02-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitem_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(0, 'Cart_Stage'), (1, 'Order_Confirmed'), (2, 'Order_Processed'), (3, 'Order_Delivered'), (4, 'Order_Rejected')], default=0),
        ),
    ]
