# Generated by Django 5.0.1 on 2024-02-13 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_owner_alter_orderitem_product'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='OrderedItem',
        ),
    ]
